# Generated by Django 5.2.10 on 2026-04-16 14:00

import django.db.models.deletion
import django_lifecycle.mixins
import pulpcore.app.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("python", "0021_pythonrepository_upload_duplicate_filenames"),
    ]

    operations = [
        migrations.CreateModel(
            name="PythonBlocklistEntry",
            fields=[
                (
                    "pulp_id",
                    models.UUIDField(
                        default=pulpcore.app.models.base.pulp_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pulp_created", models.DateTimeField(auto_now_add=True)),
                ("pulp_last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.TextField(default=None, null=True)),
                ("version", models.TextField(default=None, null=True)),
                ("filename", models.TextField(default=None, null=True)),
                ("added_by", models.TextField(default="")),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocklist_entries",
                        to="python.pythonrepository",
                    ),
                ),
            ],
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
